# Generated by Django 3.1.2 on 2020-11-06 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0004_auto_20201103_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='HomeworkMark',
        ),
        migrations.RenameModel(
            old_name='Marked',
            new_name='MarkedTest',
        ),
    ]
