export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const GET_GRADED_ASSIGNMENT_LIST_START =
  "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL =
  "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS =
  "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";

export const GET_TEST_LIST_START = "GET_TEST_LIST_START";
export const GET_TEST_LIST_FAIL = "GET_TEST_LIST_FAIL";
export const GET_TEST_LIST_SUCCESS = "GET_TEST_LIST_SUCCESS";

export const GET_TEST_DETAIL_START = "GET_TEST_DETAIL_START";
export const GET_TEST_DETAIL_FAIL = "GET_TEST_DETAIL_FAIL";
export const GET_TEST_DETAIL_SUCCESS = "GET_TEST_DETAIL_SUCCESS";

export const CREATE_TEST_START = "CREATE_TEST_START";
export const CREATE_TEST_FAIL = "CREATE_TEST_FAIL";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";

export const GET_GRADED_TEST_LIST_START =
  "GET_GRADED_TEST_LIST_START";
export const GET_GRADED_TEST_LIST_FAIL =
  "GET_GRADED_TEST_LIST_FAIL";
export const GET_GRADED_TEST_LIST_SUCCESS =
  "GET_GRADED_TEST_LIST_SUCCESS";

export const CREATE_GRADED_TEST_START =
  "CREATE_GRADED_TEST_START";
export const CREATE_GRADED_TEST_FAIL =
  "CREATE_GRADED_TEST_FAIL";
export const CREATE_GRADED_TEST_SUCCESS =
  "CREATE_GRADED_TEST_SUCCESS";

export const GET_GRADED_TEST_DETAIL_START = "GET_GRADED_TEST_DETAIL_START";
export const GET_GRADED_TEST_DETAIL_FAIL = "GET_GRADED_TEST_DETAIL_FAIL";
export const GET_GRADED_TEST_DETAIL_SUCCESS = "GET_GRADED_TEST_DETAIL_SUCCESS";

export const HOMEWORK_LIST_START =
  "HOMEWORK_LIST_START";
export const HOMEWORK_LIST_FAIL =
  "HOMEWORK_LIST_FAIL";
export const HOMEWORK_LIST_SUCCESS =
  "HOMEWORK_LIST_SUCCESS";

export const UPLOAD_HOMEWORK_START =
  "UPLOAD_HOMEWORK_START";
export const UPLOAD_HOMEWORK_FAIL =
  "UPLOAD_HOMEWORK_FAIL";
export const UPLOAD_HOMEWORK_SUCCESS =
  "UPLOAD_HOMEWORK_SUCCESS";

export const HOMEWORK_DOWNLOAD_START = "HOMEWORK_DOWNLOAD_START";
export const HOMEWORK_DOWNLOAD_FAIL = "HOMEWORK_DOWNLOAD_FAIL";
export const HOMEWORK_DOWNLOAD_SUCCESS = "HOMEWORK_DOWNLOAD_SUCCESS";

export const MATERIAL_LIST_START =
  "MATERIAL_LIST_START";
export const MATERIAL_LIST_FAIL =
  "MATERIAL_LIST_FAIL";
export const MATERIAL_LIST_SUCCESS =
  "MATERIAL_LIST_SUCCESS";

export const UPLOAD_MATERIAL_START =
  "UPLOAD_MATERIAL_START";
export const UPLOAD_MATERIAL_FAIL =
  "UPLOAD_MATERIAL_FAIL";
export const UPLOAD_MATERIAL_SUCCESS =
  "UPLOAD_MATERIAL_SUCCESS";

export const MATERIAL_DOWNLOAD_START = "MATERIAL_DOWNLOAD_START";
export const MATERIAL_DOWNLOAD_FAIL = "MATERIAL_DOWNLOAD_FAIL";
export const MATERIAL_DOWNLOAD_SUCCESS = "MATERIAL_DOWNLOAD_SUCCESS";

export const MARKED_TEST_LIST_START =
  "MARKED_TEST_LIST_START";
export const MARKED_TEST_LIST_FAIL =
  "MARKED_TEST_LIST_FAIL";
export const MARKED_TEST_LIST_SUCCESS =
  "MARKED_TEST_LIST_SUCCESS";

export const UPLOAD_MARKED_TEST_START =
  "UPLOAD_MARKED_TEST_START";
export const UPLOAD_MARKED_TEST_FAIL =
  "UPLOAD_MARKED_TEST_FAIL";
export const UPLOAD_MARKED_TEST_SUCCESS =
  "UPLOAD_MARKED_TEST_SUCCESS";

export const MARKED_TEST_DOWNLOAD_START = "MARKED_TEST_DOWNLOAD_START";
export const MARKED_TEST_DOWNLOAD_FAIL = "MARKED_TEST_DOWNLOAD_FAIL";
export const MARKED_TEST_DOWNLOAD_SUCCESS = "MARKED_TEST_DOWNLOAD_SUCCESS";

export const MARKS_LIST_START =
  "MARKS_LIST_START";
export const MARKS_LIST_FAIL =
  "MARKS_LIST_FAIL";
export const MARKS_LIST_SUCCESS =
  "MARKS_LIST_SUCCESS";

export const UPLOAD_MARKS_START =
  "UPLOAD_MARKS_START";
export const UPLOAD_MARKS_FAIL =
  "UPLOAD_MARKS_FAIL";
export const UPLOAD_MARKS_SUCCESS =
  "UPLOAD_MARKS_SUCCESS";

export const MARKS_DOWNLOAD_START = "MARKS_DOWNLOAD_START";
export const MARKS_DOWNLOAD_FAIL = "MARKS_DOWNLOAD_FAIL";
export const MARKS_DOWNLOAD_SUCCESS = "MARKS_DOWNLOAD_SUCCESS";

export const GRADED_LIST_START =
  "GRADED_LIST_START";
export const GRADED_LIST_FAIL =
  "GRADED_LIST_FAIL";
export const GRADED_LIST_SUCCESS =
  "GRADED_LIST_SUCCESS";

export const UPLOAD_GRADED_START =
  "UPLOAD_GRADED_START";
export const UPLOAD_GRADED_FAIL =
  "UPLOAD_GRADED_FAIL";
export const UPLOAD_GRADED_SUCCESS =
  "UPLOAD_GRADED_SUCCESS";

export const GRADED_DOWNLOAD_START = "GRADED_DOWNLOAD_START";
export const GRADED_DOWNLOAD_FAIL = "GRADED_DOWNLOAD_FAIL";
export const GRADED_DOWNLOAD_SUCCESS = "GRADED_DOWNLOAD_SUCCESS";

export const GET_CLASS_LIST_START = "GET_CLASS_LIST_START";
export const GET_CLASS_LIST_FAIL = "GET_CLASS_LIST_FAIL";
export const GET_CLASS_LIST_SUCCESS = "GET_CLASS_LIST_SUCCESS";

export const GET_CLASS_DETAIL_START = "GET_CLASS_DETAIL_START";
export const GET_CLASS_DETAIL_FAIL = "GET_CLASS_DETAIL_FAIL";
export const GET_CLASS_DETAIL_SUCCESS = "GET_CLASS_DETAIL_SUCCESS";