# Generated by Django 3.1.2 on 2020-11-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201108_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradedpractice',
            old_name='assignment',
            new_name='practice',
        ),
    ]
