# Generated by Django 3.1.2 on 2020-11-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20201105_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
    ]
