# Generated by Django 3.1.2 on 2020-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_remove_class_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
